<?php

/**
 * @file
 * Module file.
 */

function pr_site_customization_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'ct_house_on_rent_node_form') {
    drupal_set_title('Post Your Property Online For Free');
    // $form['field_ct_hor_for_sale']['#access'] = 0;
  }
  if ($form_id == 'ef_interested_in_property_entityform_edit_form') {
    $form['field_ef_interested_in_property']['#attributes']['class'][] = 'hidden';
    $form['extra'] = array(
      '#type' => 'markup',
      '#markup' => 'X',
      '#prefix' => '<div class="close-interested-form">',
      '#suffix' => '</div>',
    );
  }
}

function pr_site_customization_theme() {
  return array(
    'footer_second_last' => array(
      'template' => 'footer-second-last',
      'path' => drupal_get_path('module', 'pr_site_customization') . '/templates',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function pr_site_customization_block_info() {
  $blocks = array();
  $blocks['footer_second_last_block'] = array(
    'info' => t('Footer second last block'),
  );
  $blocks['contact_home_owner_button'] = array(
    'info' => t('contact home owner button'),
  );
  $blocks['register_for_free'] = array(
    'info' => t('Register for free'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pr_site_customization_block_view($delta='') {
  $output = array();
  switch($delta) {
    case 'footer_second_last_block':
      $output['subject'] = '';
      $output['content'] = footer_block_contents();
      break;
    case 'contact_home_owner_button':
      $output['subject'] = '';
      $output['content'] = contact_home_owner_button();
      break;
    case 'register_for_free':
      $output['subject'] = '';
      $output['content'] = register_for_free();
      break;
  }

  return $output;
}

function register_for_free() {
  if (user_is_anonymous()) {
    $block_output = '<a class="register-for-free-link" href="/user">Free Registration</a>';
  }
  else {
    $block_output = '<a class="register-for-free-link" href="/list-your-property">Post Property For Free</a>';
  }

  return $block_output;
}

function footer_block_contents() {
  $variables['footer_menu_block'] = module_invoke('menu', 'block_view', 'menu-footer-menu');
  $variables['contact_us_block'] = module_invoke('webform', 'block_view', 'client-block-5');

  $block_output = theme('footer_second_last', $variables);

  return $block_output;
}

function contact_home_owner_button() {
  $nid = arg(1);
  $output = '<div class="pl_buttons">';
  $output .= '<div class="pl_interested btn-primary" data=' . $nid . '>Request Call back</div>';
  $output .= '</div>';

  return $output;
}
